---
# Set up Hockeypuck user, paths
- group: name=hockeypuck
- user: name=hockeypuck group=hockeypuck createhome=no
- file: path={{ item }} owner=hockeypuck group=hockeypuck mode=0755 state=directory
  with_items:
    - /var/lib/hockeypuck
    - /var/log/hockeypuck
    - /etc/hockeypuck

# Install Hockeypuck service & binary
- template: src=hockeypuck.conf.j2 dest=/etc/init/hockeypuck.conf owner=hockeypuck group=hockeypuck mode=0644
- local_action: shell go build -o {{ item }} github.com/hockeypuck/server/cmd/{{ item }}
  sudo: no
  run_once: true
  with_items:
    - hockeypuck
    - hockeypuck-load
    - hockeypuck-pbuild
- service: name=hockeypuck state=stopped
- copy: src={{ item }} dest=/usr/bin/{{ item }} mode=0755
  with_items:
    - hockeypuck
    - hockeypuck-load
    - hockeypuck-pbuild

# Install MongoDB
- apt: pkg=mongodb-server update_cache=yes state=latest
- service: name=mongodb state=stopped

